name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./...

      - name: Test
        if: '!cancelled()'
        run: go test -v ./...

      - name: Vet
        if: '!cancelled()'
        run: go vet -v ./...

      - name: Fmt
        if: '!cancelled()'
        run: test -z $(gofmt -l .)
